### ISSUE TITLE
[BUG] New module installation doesn't load immediately

### ISSUE THREAD

**Issue by AsyncRes** [LSPosed/LSPosed#1025]
**What happened?**
When install new module, LSPosed shows notification that there is new module installed. But module doesn't load immediately after enabling it. Yes I tried force closing reopening the hooked app multiple time, still module doesn't load. Log doesn't show anything related to module load. If I go inside LSPosed module tab, and then click again on the new module from Module list, and then force close the hooked app, that's when it works and that time log also shows that module is loaded. 
This problem started after new update of LSPosed, but I'm not sure which version brought this bug, as I have updated multiple times.

Related Bug: LSPosed also doesn't detect module update deployed from Android Studio. I'm developing a module, but after some changes and build/run to my phone, LSPosed simply doesn't detect that the module is updated. I have to build/run once and then clear module app data from phone and then build/run again. that's when it detects module is updated. It's really hard to develop module this way.

**Xposed Module List**
Any module.

**Magisk Module List**
Riru + LSPosed

**Versions**

Android:
11

Magisk:
23

Riru:
26

LSPosed:
1.5.2

**Related Logs**
I enabled verbose log, but nothing shows in log. Module simply doesn't load. Only after trying what i mentioned, then when module loads, it shows that the module is loaded.

**Comment by yujincheng08** [comment]
Since you are Android R, you should first try to disable the deploy optimization:
![image](https://user-images.githubusercontent.com/5022927/131254183-7af45953-49d7-49ab-96c5-c00cc4ca0c94.png)

Notice that every time a module is installed or updated, LSPosed Manager will show a notification. If there's no notification, the package broadcast receiver may be broken. Debug version will log more details about the package broadcast receiver.
