### ISSUE TITLE
[Feature Request] Global Hooking Option

### ISSUE THREAD

**Issue by cumhuronat** [LSPosed/LSPosed#1195]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I want to hook a method inside an sdk that is being used in multiple applications. Currently I will have to enable the module I have created for each additional app I install.

### Describe the solution you'd like/描述你想要的解决方案

Creating an option to enable the module for all applications.

**Comment by etmatrix** [comment]
A way for resolve your issue is use Module API #9 when will be avaiable.
Temporarly you can use [this](https://gist.github.com/etmatrix/a929df3ec15a55d3b0483cff45fd71bb) gist, require root permission and change the database of lsposed and restart the daemon.
[Here](https://github.com/LSPosed/LSPosed/discussions/965) there is a discussion
You can execute on intent ACTION_PACKAGE_INSTALL and choose if enable or not your module for the app installed.
You can use org.smali:dexlib2 for analyze apk and understand if the app use that specific sdk.
I think all this is better to hook all applications.
