### ISSUE TITLE
[BUG] Freezer frozen app problem

### ISSUE THREAD

**Issue by book-devil** [LSPosed/LSPosed#253]
在冻结这个app之前。我已经在lspised的作用域上勾选这个app。
可是重新解冻后，显示没有勾选。

**Comment by book-devil** [comment]
冻结app前，已经在作用域勾选了。解冻后显示没有勾选。

**Comment by RikkaW** [comment]
Freeze from "Island" or other "device/profile owner" apps is actually "hidden" which is treated as uninstalled by the system.

@yujincheng08 The backend needs to do some extra check for the `PACKAGE_REMOVED` broadcast.

1. Check if `getApplicationInfo` with `MATCH_UNINSTALLED_PACKAGES` does not returns null
2. Check if the `ApplicationInfo#uid` matches the uid from the action (`EXTRA_UID`)
3. Check if `ApplicationInfo#dataDir` and `ApplicationInfo#sourceDir` exists

(Use `getApplicationHiddenSettingAsUser` does not help, since it will return true on error, includes the real uninstallation)

**Comment by yujincheng08** [comment]
@RikkaW 么么哒
