### ISSUE TITLE
[BUG] Phone enters bootloop after installing LSPosed

### ISSUE THREAD

**Issue by r1Ns3** [LSPosed/LSPosed#472]
**什么情况/What happened?**
After reboot on installation of LSPosed from Magisk Manager, the phone went into bootloop. 
Did not have any xposed modules because I never had xposed or edxposed installed. 

**Xposed模块列表/Xposed Module List**

None

**Magisk模块列表/Magisk Module List**
Riru Core, busybox

**版本信息/Versions**

Android: 11

Magisk: 66e30a77 (22006)

Riru: Latest

LSPosed: Latest

**相关日志/Related Logs**
[magisk_install_log_2021-04-11T20_46_43Z.log](https://github.com/LSPosed/LSPosed/files/6291560/magisk_install_log_2021-04-11T20_46_43Z.log)

**Comment by yujincheng08** [comment]
This log is invalid. Please grab log with this tool: https://t.me/hzrtools/10

**Comment by r1Ns3** [comment]
[boot.log](https://github.com/LSPosed/LSPosed/files/6291617/boot.log)

**Comment by yujincheng08** [comment]
This is caused by Magisk, which cannot finish its mounting process and leaving many so files missing. See https://github.com/topjohnwu/Magisk/issues/3976#issuecomment-790425930

It may because you are using old magisk. Please try to upgrade to latest 22.1. If the problem persist, please report to magisk.

**Comment by r1Ns3** [comment]
Yes you were right, this solved the issue. Thank you. Latest canary edition works.
