### ISSUE TITLE
[FR] Is it possible for modules to detect if xp variant is LSPosed or others?

### ISSUE THREAD

**Issue by hatsune-miku** [LSPosed/LSPosed#527]
**Detail**
Or, since LSPosed leaves a lspd_* folder in /data/misc, then will this `isLSPosed` mechanism reliable?

```kotlin
        fun isLSPosed(context: Context): Boolean {
            val prefs = context.getSharedPreferences("dummy", Context.MODE_PRIVATE)
            prefs.edit().putBoolean("dummy", false).commit()

            try {
                prefs.javaClass.getDeclaredField("mFile").apply {
                    isAccessible = true
                    return (get(prefs) as File).absolutePath.contains("lspd_")
                }
            }
            catch (e: Throwable) {
                return false
            }
        }
```

**Comment by yujincheng08** [comment]
We are actually working on module API, which provides a way for modules to get information about the framework. You can try to use it after we finished it. See it if you have any suggestion: Xposed-Modules-Repo/XposedService#1

BTW, lsp_xxx is not reliable because it only used to store preferences. Once XRemotePreference which is a preference via IPC is finished, this folder would be deprecated.
