### ISSUE TITLE
[BUG] IllegalArgumentException

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#69]
```
02-04 15:15:25.516  3155  3155 E LSPosed : error occur when generating dex.
02-04 15:15:25.516  3155  3155 E LSPosed : java.lang.IllegalArgumentException: requested Lde/robv/android/xposed/LspHooker; but was Lde/robv/android/xposed/LspHooker;
02-04 15:15:25.516  3155  3155 E LSPosed : 	at external.com.android.dx.Code.coerce(Code.java:267)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at external.com.android.dx.Code.getParameter(Code.java:250)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.dexmaker.HookerDexMaker.generateSetupMethod(HookerDexMaker.java:208)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.dexmaker.HookerDexMaker.doGenerate(HookerDexMaker.java:190)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.dexmaker.HookerDexMaker.doMake(HookerDexMaker.java:171)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.dexmaker.HookerDexMaker.start(HookerDexMaker.java:132)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.dexmaker.DynamicBridge.hookMethod(DynamicBridge.java:42)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at io.github.lsposed.lspd.yahfa.config.YahfaHookProvider.hookMethod(YahfaHookProvider.java:19)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at de.robv.android.xposed.XposedBridge.hookMethodNative(XposedBridge.java:465)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:242)
02-04 15:15:25.516  3155  3155 E LSPosed : 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
```
Android version: 10
Android sdk: 29
LSPosed version: v0.5.3.0
LSPosed api: 93
Riru version: v23.4 (54)
Riru api: 10
Magisk: 21.4 (21400)

**Comment by yujincheng08** [comment]
Never gonna happen.

https://github.com/LSPosed/LSPosed/blob/fc1bf22eda9d0a2ef7cdb3a10bb14f58d607773e/core/src/main/java/external/com/android/dx/Code.java#L266-L269

This code snippet shows it will compare two `Local`s, and the comparison of `Local` is done by:

https://github.com/LSPosed/LSPosed/blob/fc1bf22eda9d0a2ef7cdb3a10bb14f58d607773e/core/src/main/java/external/com/android/dx/TypeId.java#L139-L142

comparing their `name`.

And from your log, the two `Local`s have the same `toString` result and the `toString` of `Local` is

https://github.com/LSPosed/LSPosed/blob/fc1bf22eda9d0a2ef7cdb3a10bb14f58d607773e/core/src/main/java/external/com/android/dx/TypeId.java#L150-L152

exactly the `name`.

So as long as the log shows their name is the same, they will never be inequal.

Those codes are thread-safe because a new `dexmaker` is generated every time.
