### ISSUE TITLE
[BUG] A certain chance of causing the phone to restart

### ISSUE THREAD

**Issue by j0912H97** [LSPosed/LSPosed#832]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

![Screenshot_20210729-122224_LSPosed](https://user-images.githubusercontent.com/62490010/127426665-f5eb1e53-fecc-41df-82b3-75286972d57f.jpg)

**Magisk模块列表/Magisk Module List**
![Screenshot_20210729-122414](https://user-images.githubusercontent.com/62490010/127426708-9923a58a-0459-49dd-bac9-3ab89ac26c99.jpg)

 
**版本信息/Versions**

Android:11（oneui3.1)

Magisk: 1eb83ad8-alpha-27

Riru: 26.0.3

LSPosed: 1.4.7(5826)debug

**相关日志/Related Logs**

**Comment by j0912H97** [comment]
[boot.zip](https://github.com/LSPosed/LSPosed/files/6897761/boot.zip)

**Comment by j0912H97** [comment]
[log.ZIP](https://github.com/LSPosed/LSPosed/files/6904240/log.ZIP)

**Comment by j0912H97** [comment]
[突然重启log.ZIP](https://github.com/LSPosed/LSPosed/files/6905906/log.ZIP)

**Comment by yujincheng08** [comment]
those are bootlog but not crash log so we cannot find anything useful.
besides, it's most likely caused by modules.
Moreover, some Samsung users reported that their phone occasionally soft-reset because of knox or something like that.

Please confirm that the soft-reset is really caused by LSPosed itself, rather than its modules or magisk modules. Please disable all LSPosed modules and Magisk modules except for LSPosed itself and Riru and check if the problem reproduced. If so, please also disable LSPosed and keep only Riru activated.

BTW, LSPosed automatically backup logs from previous boot. So the best log should be in /data/adb/lspd/log.bk. Please enable verbose log before collecting logs.

Issue will be reopened if it confirms to be LSPosed's side.
