### ISSUE TITLE
Some system applications cannot be found, such as: com.miui.system for MIUI system, note that it is not SystemUI[FR] 

### ISSUE THREAD

**Issue by mrbingdian** [LSPosed/LSPosed#835]
**Detail**:
Some system applications cannot be found, such as: com.miui.system for MIUI system, note that it is not SystemUI

**Comment by yujincheng08** [comment]
Our injection is actually in *process* unit rather than in package unit. That means if the package has no components (activity, receiver, provider or service), we will filter them out since there's no single process for it.

See these codes:
https://github.com/LSPosed/LSPosed/blob/5f250e860c450ba59459e4d0a6837ce73a10012f/core/src/main/java/org/lsposed/lspd/service/PackageService.java#L155-L171

`com.miui.system` has no single process and will be loaded by the process of another package. You should select the package that loads this package instead. Notice that we don't know and have no way to know which process will load this package.
